title: Marty Ryan
description:Professional Certificates

- Microsoft Data Science Associate (DP-100)
-	Microsoft Azure fundamentals (AZ-900)
-	Cisco Routing and switching professional Certificate
-	VCP – VMware Certified Professional 2022 Certificate
-	VCP – VMware Certified Professional Digital Workspace
-	Citrix Virtual Apps and Desktops on premise and on Cloud – CCA-V certificate
-	Completed Citrix Virtual Apps and Desktop Advanced Administration course – CCV-V
-	Completed Citrix Provisioning Administration certificate
-	Citrix Virtual Apps and Desktop service with Microsoft Azure course
show_downloads: true
theme: jekyll-theme-minimal
